require: rubocop-performance

Rails:
  Enabled: true

AllCops:
  Exclude:
    - Guardfile
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - test/test_helper.rb
    - vendor/**/*
  TargetRailsVersion: 5.2

Layout/AccessModifierIndentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - app/models/forecast.rb

Lint/Void:
  Exclude:
    - lib/tasks/surfline.rake

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Size:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
